<div class="page-title">
    <h1>Store Locator</h1>
</div>
<?php
$bootstrap = \Magento\Framework\App\Bootstrap::create(BP, $_SERVER);
$objectManager = $bootstrap->getObjectManager();
$countryHelper = $objectManager->get('Magento\Directory\Model\Config\Source\Country'); 
$countryFactory = $objectManager->get('Magento\Directory\Model\CountryFactory');
$countries = $countryHelper->toOptionArray();
$mediaUrl = $this->getStoreManager()->getStore()->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA);
$LatLng = array();
$data = $this->getRequest()->getPost();
?>
<div class="storelocator">
	<div class="search">
		<table border="0" id="search-store">
		    <tbody>
			    <tr>
			        <td style="width: 45%">
			            <form action="<?php echo $block->getUrl('storelocator/storelocator/index'); ?>" method="post" id="addressSearch">
			                <div class="fieldset">
			                    <h2 class="legend">Search Store</h2>
			                    <ul class="form-list store-list">
									<li>
			                            <label for="country">Country</label>
			                            <div class="input-box">
			                            	<select name="country" id="country" class="select" title="Country">
				                            	<?php foreach ($countries as $country): ?>
													<option <?php if($data['country'] == $country['value']) { echo 'selected'; } ?> value="<?php echo $country['value'] ?>"><?php echo $country['label'] ?></option>
				                            	<?php endforeach; ?>
			                            	</select>
			                            </div>
			                        </li>
			                        <li>
			                            <label for="state">State</label>
			                            <div class="input-box">
			                                <input type="text" name="state" id="state" value="<?php echo $data['state'] ?>" title="state" class="input-text">
			                            </div>
			                        </li>
			                        <li>
			                            <label for="city">City</label>
			                            <div class="input-box">
			                                <input type="text" name="city" id="city" value="<?php echo $data['city'] ?>" title="City" class="input-text">
			                            </div>
			                        </li>
			                        <li>
			                            <label for="zipcode">Zipcode</label>
			                            <div class="input-box">
			                                <input type="text" name="zipcode" id="zipcode" value="<?php echo $data['zipcode'] ?>" title="Zipcode" class="input-text">
			                            </div>
			                        </li>
			                        <li>
			                            <button type="submit" title="Search" class="button"><span><span>Search</span></span></button>
			                            <?php 
			                            	$resetUrl = $block->getUrl('storelocator/storelocator/');
			                            ?>
			                            <button type="reset" title="Reset" class="button" onclick="window.location.assign('<?php echo $resetUrl ?>')"><span><span>Reset</span></span></button>
			                        </li>
			                    </ul>
			                </div>
			            </form>
			        </td>
			    </tr>
			</tbody>
		</table>
	</div>
	<div class="data" style="width:100%">
		<div class="store_list" style="width:50%;float:left;">
			<?php
			$i = 1;
			$collections = $block->getCollection();
			if(count($collections)):
				foreach ($collections as $col): ?>
					<div class="store-<?php echo $col->getId() ?>">
						<img height="100px" width="100px" src="<?php echo $mediaUrl.'/'.$col->getStoreLogo() ?>">
					</div>
					<div class="store_name">
						<p><?php echo $col->getStoreName(); ?></p>
					</div>
					<div class="phone">
						<p><?php echo $col->getPhone(); ?></p>
					</div>
					<div class="website">
						<p><a href="<?php echo $col->getWebsite(); ?>"><?php echo $col->getWebsite(); ?></a></p>
					</div>
					<div class="email">
						<p><?php echo $col->getEmail(); ?></p>
					</div>
					<div class="opening_hours">
						<p><?php echo $col->getOpeningHours(); ?></p>
					</div>
					<div class="street_address">
						<p><?php echo $col->getStreetAddress(); ?>,<?php echo $col->getCity(); ?></p>
						<p><?php echo $col->getState(); ?>,<?php echo $col->getCountry(); ?>,<?php echo $col->getZipcode(); ?></p>
					</div>
					<?php 
                    	$viewUrl = $block->getUrl('storelocator/storelocator/view',array('id'=>$col->getId()));
                    ?>
					<div class="button">
						<button type="submit" title="view_more" onclick="window.location.assign('<?php echo $viewUrl ?>')" class="button"><span><span>View More</span></span></button>
						<button type="submit" onclick="initMapOnClick(<?php echo $col->getLatitude() ?>,<?php echo $col->getLongitude() ?>,'<?php echo $col->getStoreName(); ?>',<?php echo $col->getZoomLevel(); ?>,<?php echo $col->getRadius(); ?>)" title="show_map" class="button"><span><span>Show Map</span></span></button>
					</div>
				<?php
					$LatLng[] = array($col->getLatitude(),$col->getLongitude(),$col->getStoreName());
					$i++;
				endforeach;
			else:
				?>
				<div class="no-record">No Record Found.</div>
		<?php endif; ?>
				<div style="clear: both"></div>
 
		        <div class="toolbar-bottom">
		           <div class="toolbar bottom">
		              <?php echo $block->getPagerHtml(); ?>
		           </div>
		        </div>
		</div>
		<div class="map" style="width:50%;height:380px;float:right;">
			<div id="map"></div>
		</div>
	</div>
</div>
<script async defer
    src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAhhL62mRn6t8WlnOSrljP1Iq-JX_efxYY&callback=initMap">
    </script>
    <script>
	    function initMap()
	     {
	     	var data = <?php echo json_encode( $LatLng ) ?>;
	        var myLatLng = {lat: <?php echo $collections->getFirstItem()->getLatitude(); ?>, lng: <?php echo $collections->getFirstItem()->getLongitude(); ?>};
	        var map = new google.maps.Map(document.getElementById('map'), {
	          zoom: 4,
	          center: myLatLng
	        });
	        var infowindow = new google.maps.InfoWindow();
	        var marker, i;
		    for (i = 0; i < data.length; i++) {  
			    marker = new google.maps.Marker({
			        position: new google.maps.LatLng(data[i][0], data[i][1]),
			        map: map
			    });
			    google.maps.event.addListener(marker, 'click', (function(marker, i) {
			        return function() {
			          infowindow.setContent(data[i][2]);
			          infowindow.open(map, marker);
			        }
			    })(marker, i));
		    }
	    }
    </script>
    <script>
	    function initMapOnClick(lat,lng,store,zoom,radius) 
	     {
	     	if(!radius)
	     	{
	     		radius = 16093;
	     	}
	        var myLatLng = {lat: lat, lng: lng};
	        var map = new google.maps.Map(document.getElementById('map'), {
	          zoom: zoom,
	          center: myLatLng
	        });
	        var infowindow = new google.maps.InfoWindow();
	        var marker, i;  
		    marker = new google.maps.Marker({
		        position: new google.maps.LatLng(lat,lng),
		        map: map
		    });
		    var circle = new google.maps.Circle({
				  map: map,
				  radius: radius,    // 10 miles in metres
				  fillColor: '#AA0000'
				});
				circle.bindTo('center', marker, 'position');
		    google.maps.event.addListener(marker, 'click', (function(marker, i) {
		        return function() {
		          infowindow.setContent(store);
		          infowindow.open(map, marker);
		        }
		    })(marker, i));
	    }
    </script>

<style>
      html, body {
        height: 100%;
        margin: 0;
        padding: 0;
      }
      #map {
        height: 100%;
      }
      li
	  {
	  	list-style: none;
	  }
    </style>
<script type="text/javascript">
require(['jquery'],function($){
	jQuery("#addressSesarch").submit(function(){
		var formData = {
					country:jQuery('#country').val(),
					state:jQuery('#state').val(),
					city:jQuery('#city').val(),
					zipcode:jQuery('#zipcode').val(),
					}; //Array 
		jQuery.ajax({
		    url : "<?php echo $block->getUrl('storelocator/storelocator/search'); ?>",
		    type: "POST",
		    data : formData,
		    success: function(data, textStatus, jqXHR)
		    {
		        console.log(data);
		    },
		    error: function (jqXHR, textStatus, errorThrown)
		    {
		 		alert('Error Message: '+textStatus);
     			alert('HTTP Error: '+errorThrown);
		    }
		});
	});
});
</script>